"Syntax highlighting
syntax on

"Colorscheme
colorscheme ghdark
hi Normal guibg=NONE ctermbg=NONE

"Always show command
set showcmd

"Show matching special characters (parentheses, brackets, etc...)
set showmatch

"Enable the wildmenu (auto completion for vim command)
set wildmenu

"Highlight the line where cursor is
set cursorline
highlight CursorLine ctermbg=black

"Show line numbers
set nu

"Enable incremental searching
set is

"Highlight searched patterns
set hls

"Enable mouse support
set mouse=a

"Get back to the last known cursor position in file
au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal g`\"" | endif

"Change 'conf' filetype to 'confini' for a better syntax highlighting
autocmd FileType conf set ft=confini
